#!/usr/bin/env python3
"""Streaming extension and F3 microscope for notes.md section 19.

The extension scan keeps only aggregate counts and deterministic sample
reservoirs.  Candidate primes p == 1 (mod 24) are generated by a segmented
sieve on p = 24*k+1, so the memory footprint is independent of the bound.

Examples:
    uv run --with sympy python frontier_extension.py scan \
        --start 100000000 --bound 10000000000 --workers 12 \
        --output extension-scan.json
    uv run --with sympy python frontier_extension.py microscope \
        --bound 10000000000 --workers 12 --extension extension-scan.json \
        --output microscopy.json
"""

from __future__ import annotations

import argparse
import json
import math
import multiprocessing as mp
import random
import time
from collections import Counter
from math import gcd
from pathlib import Path

from sympy import jacobi_symbol, primerange

from frontier_compute import MODULI, divisor_hit, reachable_residues, subgroup_generated


def segmented_hard_primes(lo: int, hi: int) -> list[int]:
    """Return primes p in [lo,hi) with p == 1 (mod 24)."""
    if hi <= lo:
        return []
    k_lo = max(0, (lo - 1 + 23) // 24)
    k_hi = max(k_lo, (hi - 1 + 23) // 24)
    flags = bytearray(b"\x01") * (k_hi - k_lo)
    for q in primerange(5, math.isqrt(hi - 1) + 1):
        # 24*k+1 == 0 (mod q).  Starting at q^2 avoids deleting q itself.
        residue = (-pow(24, -1, q)) % q
        first_k = max(k_lo, (q * q - 1 + 23) // 24)
        first_k += (residue - first_k) % q
        index = first_k - k_lo
        if index < len(flags):
            count = (len(flags) - 1 - index) // q + 1
            flags[index::q] = b"\x00" * count
    if k_lo == 0 and flags:
        flags[0] = 0  # p=1
    return [24 * (k_lo + i) + 1 for i, flag in enumerate(flags) if flag]


def minimal_interleaved(p: int) -> tuple[int, int]:
    for w in MODULI:
        n_b = (p + w) // 4
        if divisor_hit(n_b, w)[0]:
            return p, w
        n_a = (p * w + 1) // 4
        if divisor_hit(n_a, w)[0]:
            return p, w
    raise RuntimeError(f"search guard exhausted at p={p}")


def scan_interval(
    start: int, bound: int, workers: int, block_span: int, baseline_max: int = 59
) -> dict:
    """Scan [start,bound), retaining aggregates rather than per-prime rows."""
    if start >= bound:
        raise ValueError("start must be below bound")
    histogram = Counter()
    records = []
    running = baseline_max
    count = 0
    max_prime = None
    sieve_seconds = scan_seconds = 0.0
    block_rows = []
    context = mp.get_context("fork")
    pool = context.Pool(workers) if workers > 1 else None
    try:
        lo = start
        while lo < bound:
            hi = min(bound, lo + block_span)
            t0 = time.perf_counter()
            primes = segmented_hard_primes(lo, hi)
            sieve_seconds += time.perf_counter() - t0
            t0 = time.perf_counter()
            iterator = (
                map(minimal_interleaved, primes)
                if pool is None
                else pool.imap(minimal_interleaved, primes, chunksize=256)
            )
            local = Counter()
            local_count = 0
            for p, wstar in iterator:
                local[wstar] += 1
                local_count += 1
                max_prime = p
                if wstar > running:
                    records.append({"p": p, "w_star": wstar})
                    running = wstar
            elapsed = time.perf_counter() - t0
            scan_seconds += elapsed
            histogram.update(local)
            count += local_count
            block_rows.append(
                {
                    "lo": lo,
                    "hi": hi,
                    "prime_count": local_count,
                    "scan_seconds": elapsed,
                    "primes_per_scan_second": local_count / elapsed,
                }
            )
            print(json.dumps(block_rows[-1]), flush=True)
            lo = hi
    finally:
        if pool is not None:
            pool.close()
            pool.join()
    return {
        "range": {"start_inclusive": start, "bound_exclusive": bound},
        "max_p": max_prime,
        "prime_count": count,
        "baseline_max_w_star": baseline_max,
        "max_w_star": max([baseline_max, *histogram.keys()]),
        "new_records": records,
        "histogram_tail": {str(w): histogram[w] for w in sorted(histogram) if w >= 35},
        "timing": {
            "workers": workers,
            "block_span": block_span,
            "sieve_seconds": sieve_seconds,
            "scan_seconds": scan_seconds,
            "primes_per_scan_second": count / scan_seconds,
            "blocks": block_rows,
        },
    }


def pair_data(p: int, w: int, half: str) -> tuple[str, int, dict[int, int], int]:
    """Classify one half-pair, also returning n, factorization, and target."""
    n = (p + w) // 4 if half == "B" else (p * w + 1) // 4
    literal, fac = divisor_hit(n, w)
    target = (-n) % w
    assert literal == (target in reachable_residues(fac, w))
    if literal:
        return "success", n, fac, target
    if gcd(n, w) != 1 or any(gcd(prime, w) != 1 for prime in fac):
        category = "F0"
    elif jacobi_symbol(target, w) == -1 and all(
        jacobi_symbol(prime, w) == 1 for prime in fac
    ):
        category = "F1"
    elif target not in subgroup_generated(fac, w):
        category = "F2"
    else:
        category = "F3"
    return category, n, fac, target


def minimum_cap_deficit(fac: dict[int, int], w: int, target: int) -> dict:
    """Exact min-plus DP for the exponent excess needed to reach target.

    For a generator g of order o, every residue g^e has a representative with
    0 <= e < o; larger representatives only add cost after the cap 2*v_g(n).
    The DP retains all optimal sets of primes carrying positive excess and one
    canonical exponent vector for each such set.
    """
    factors = sorted(fac.items())
    # residue -> (cost, {carrier-index-frozenset: exponent tuple})
    dp: dict[int, tuple[int, dict[frozenset[int], tuple[int, ...]]]] = {
        1: (0, {frozenset(): ()})
    }
    for index, (prime, valuation) in enumerate(factors):
        generator = prime % w
        options = []
        power = 1
        exponent = 0
        while True:
            excess = max(0, exponent - 2 * valuation)
            options.append((power, exponent, excess))
            power = power * generator % w
            exponent += 1
            if power == 1:
                break
            assert exponent <= w
        new: dict[int, tuple[int, dict[frozenset[int], tuple[int, ...]]]] = {}
        for residue, (old_cost, old_reps) in dp.items():
            for power, exponent, excess in options:
                out = residue * power % w
                cost = old_cost + excess
                incumbent = new.get(out)
                if incumbent is None or cost < incumbent[0]:
                    incumbent = (cost, {})
                    new[out] = incumbent
                if cost != incumbent[0]:
                    continue
                for carriers, exponents in old_reps.items():
                    out_carriers = carriers | {index} if excess else carriers
                    out_exponents = exponents + (exponent,)
                    previous = incumbent[1].get(frozenset(out_carriers))
                    if previous is None or out_exponents < previous:
                        incumbent[1][frozenset(out_carriers)] = out_exponents
        dp = new
    deficit, representatives = dp[target]
    canonical = min(representatives.values())
    carrier_sets = sorted(
        ([factors[i][0] for i in carrier_set] for carrier_set in representatives),
        key=lambda values: (len(values), values),
    )
    return {
        "deficit": deficit,
        "canonical_exponents": {
            str(prime): exponent for (prime, _), exponent in zip(factors, canonical)
        },
        "optimal_carrier_prime_sets": carrier_sets,
    }


def factor_traits(fac: dict[int, int]) -> tuple[int, bool, int]:
    return len(fac), all(v == 1 for v in fac.values()), sum(fac.values()) - len(fac)


def summarize_traits(rows: list[tuple[int, bool, int]]) -> dict:
    omega = Counter(row[0] for row in rows)
    extra = Counter(row[2] for row in rows)
    values = sorted(row[0] for row in rows)
    count = len(rows)
    return {
        "count": count,
        "omega_histogram": {str(k): v for k, v in sorted(omega.items())},
        "omega_mean": sum(values) / count if count else None,
        "omega_median": values[(count - 1) // 2] if count else None,
        "squarefree_count": sum(row[1] for row in rows),
        "squarefree_fraction": (sum(row[1] for row in rows) / count if count else None),
        "extra_multiplicity_histogram": {str(k): v for k, v in sorted(extra.items())},
    }


def reservoir_primes(
    lo: int, hi: int, wanted: int, block_span: int, rng: random.Random
) -> list[int]:
    reservoir: list[int] = []
    seen = 0
    block_lo = lo
    while block_lo < hi:
        block_hi = min(hi, block_lo + block_span)
        for p in segmented_hard_primes(block_lo, block_hi):
            seen += 1
            if len(reservoir) < wanted:
                reservoir.append(p)
            else:
                j = rng.randrange(seen)
                if j < wanted:
                    reservoir[j] = p
        block_lo = block_hi
    return reservoir


def microscope(
    max_bound: int,
    workers: int,
    per_band: int,
    block_span: int,
    record_path: Path,
    extension_path: Path,
) -> dict:
    """Build the stratified/enriched sample and measure all requested traits."""
    t0 = time.perf_counter()
    rng = random.Random(0xF3194)
    bands = [
        (10**e, min(10 ** (e + 1), max_bound))
        for e in range(4, 10)
        if 10**e < max_bound
    ]

    # The dedicated low-range rescan both samples and captures every w* >= 27.
    low_primes = segmented_hard_primes(10_000, min(100_000_000, max_bound))
    selected = set()
    for lo, hi in bands:
        if lo >= 100_000_000:
            continue
        candidates = [p for p in low_primes if lo <= p < hi]
        selected.update(rng.sample(candidates, min(per_band, len(candidates))))
    enriched_rows: dict[int, int] = {}
    selected_rows: dict[int, int] = {}
    ctx = mp.get_context("fork")
    with ctx.Pool(workers) as pool:
        for p, wstar in pool.imap(minimal_interleaved, low_primes, chunksize=256):
            if p in selected:
                selected_rows[p] = wstar
            if wstar >= 27:
                enriched_rows[p] = wstar

    # At larger scales only the fixed-size reservoirs are factored.
    for lo, hi in bands:
        if lo < 100_000_000:
            continue
        chosen = reservoir_primes(lo, hi, per_band, block_span, rng)
        selected.update(chosen)
    record_data = json.loads(record_path.read_text())
    extension_data = json.loads(extension_path.read_text())
    record_ps = {row["p"] for row in record_data["interleaved_records"]}
    record_ps.update(row["p"] for row in extension_data["new_records"])
    selected.update(enriched_rows)
    selected.update(record_ps)

    missing = sorted(selected - selected_rows.keys())
    with ctx.Pool(workers) as pool:
        for p, wstar in pool.imap(minimal_interleaved, missing, chunksize=64):
            selected_rows[p] = wstar
    rows = sorted((p, selected_rows[p]) for p in selected)

    # Exact taxonomy for every failed half-pair strictly below w*.
    taxonomy = Counter()
    by_half = {"A": Counter(), "B": Counter()}
    by_w: dict[int, Counter] = {}
    f3_cases = []
    below_traits = {"F1": [], "F2": [], "F3": []}
    for p, wstar in rows:
        for w in range(3, wstar, 4):
            for half in ("B", "A"):
                category, n, fac, target = pair_data(p, w, half)
                assert category != "success", (p, w, half, wstar)
                taxonomy[category] += 1
                by_half[half][category] += 1
                by_w.setdefault(w, Counter())[category] += 1
                if category in below_traits:
                    below_traits[category].append(factor_traits(fac))
                if category == "F3":
                    deficit = minimum_cap_deficit(fac, w, target)
                    assert deficit["deficit"] >= 1
                    factors = sorted(fac)
                    carrier_sets = deficit["optimal_carrier_prime_sets"]
                    unique_options = sorted(
                        {q for group in carrier_sets for q in group}
                    )
                    if len(unique_options) != 1:
                        bind = "ambiguous"
                    elif unique_options[0] == factors[-1]:
                        bind = "largest"
                    elif unique_options[0] == factors[0]:
                        bind = "smallest"
                    else:
                        bind = "interior"
                    f3_cases.append(
                        {
                            "p": p,
                            "w": w,
                            "half": half,
                            "n": n,
                            "omega": len(fac),
                            "squarefree": all(v == 1 for v in fac.values()),
                            "factorization": {
                                str(q): e for q, e in sorted(fac.items())
                            },
                            "target": target,
                            **deficit,
                            "binding_location": bind,
                        }
                    )

    # Matched controls: all sampled p and both halves at every modulus that
    # produced an F3 failure below w*.  This keeps the modulus mix identical.
    f3_moduli = sorted({case["w"] for case in f3_cases})
    controls = {category: [] for category in ("success", "F1", "F2", "F3")}
    control_counts = Counter()
    control_tasks = (
        (p, w, half) for p, _ in rows for w in f3_moduli for half in ("B", "A")
    )
    with ctx.Pool(workers) as pool:
        for category, _, fac, _ in pool.imap(_pair_task, control_tasks, chunksize=128):
            control_counts[category] += 1
            if category in controls:
                controls[category].append(factor_traits(fac))

    deficit_hist = Counter(case["deficit"] for case in f3_cases)
    binding_hist = Counter(case["binding_location"] for case in f3_cases)
    result = {
        "sample": {
            "prime_count": len(rows),
            "range": {"min_p": rows[0][0], "max_p": rows[-1][0]},
            "stratified_random_per_decade": per_band,
            "decade_counts": {
                f"[1e{e},1e{e + 1})": sum(10**e <= p < 10 ** (e + 1) for p, _ in rows)
                for e in range(1, 10)
                if any(10**e <= p < 10 ** (e + 1) for p, _ in rows)
            },
            "enriched_w_star_ge_27_below_1e8_count": len(enriched_rows),
            "record_primes_included": sorted(record_ps),
        },
        "failures_below_w_star": {
            "pair_count": sum(taxonomy.values()),
            "taxonomy": dict(sorted(taxonomy.items())),
            "by_half": {
                half: dict(sorted(counts.items())) for half, counts in by_half.items()
            },
            "by_w": {
                str(w): dict(sorted(counts.items()))
                for w, counts in sorted(by_w.items())
            },
            "factor_traits": {
                category: summarize_traits(values)
                for category, values in below_traits.items()
            },
        },
        "f3": {
            "case_count": len(f3_cases),
            "deficit_histogram": {str(k): v for k, v in sorted(deficit_hist.items())},
            "binding_location_histogram": dict(sorted(binding_hist.items())),
            "cases": f3_cases,
        },
        "matched_controls": {
            "definition": "all sampled primes and both halves at each F3-bearing modulus",
            "moduli": f3_moduli,
            "category_counts": dict(sorted(control_counts.items())),
            "factor_traits": {
                category: summarize_traits(values)
                for category, values in controls.items()
            },
        },
        "timing_seconds": time.perf_counter() - t0,
    }
    return result


def _pair_task(task: tuple[int, int, str]):
    return pair_data(*task)


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    scan = sub.add_parser("scan")
    scan.add_argument("--start", type=int, default=100_000_000)
    scan.add_argument("--bound", type=int, required=True)
    scan.add_argument(
        "--workers", type=int, default=max(1, min(12, mp.cpu_count() // 2))
    )
    scan.add_argument("--block-span", type=int, default=100_000_000)
    scan.add_argument("--baseline-max", type=int, default=59)
    scan.add_argument("--output", required=True)
    micro = sub.add_parser("microscope")
    micro.add_argument("--bound", type=int, required=True)
    micro.add_argument(
        "--workers", type=int, default=max(1, min(12, mp.cpu_count() // 2))
    )
    micro.add_argument("--per-band", type=int, default=800)
    micro.add_argument("--block-span", type=int, default=100_000_000)
    micro.add_argument("--records", default="recorddata.json")
    micro.add_argument("--extension", default="extension-scan.json")
    micro.add_argument("--output", required=True)
    args = parser.parse_args()
    if args.command == "scan":
        result = scan_interval(
            args.start, args.bound, args.workers, args.block_span, args.baseline_max
        )
    else:
        result = microscope(
            args.bound,
            args.workers,
            args.per_band,
            args.block_span,
            Path(args.records),
            Path(args.extension),
        )
    Path(args.output).write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(
        json.dumps(
            result
            if args.command == "scan"
            else {
                "sample": result["sample"],
                "failures_below_w_star": result["failures_below_w_star"],
                "f3": {k: v for k, v in result["f3"].items() if k != "cases"},
                "matched_controls": result["matched_controls"],
                "timing_seconds": result["timing_seconds"],
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
