#!/usr/bin/env python3
"""Round-2 hostile review of POINTWISE_SIZE §§7-11 -- independent spot checks.

 1. 1 not in R(M) for all M = 3 (4), M <= MMAX            (Thm 11.2(a), notes Thm 17.3(c))
 2. log L*(T)/T                                          (Lemma 11.1)
 3. least prime = 1 mod L*(T): W(p) > T recomputed, Mordell-hard  (Thm 11.2(a), omega.txt)
 4. Lemma 8.2 (window reciprocity), brute force
 5. Cor 8.3(b): prime q, <prime factors of x> contains -1 iff some factor is a QNR mod p
 6. Lemma 9.1 incl. the n_p = 2 case (p = 5 mod 8) not covered by the written proof
 7. Lemma 11.3: constructive, Rat_q computed by brute force
 8. Prop 11.2'' step 3: explicit atom (M=3l, D=r) witnesses W <= 3l on the combined class
 9. Lemma 11.7 reduction: conditioned on n = 1 mod Q_y, W(n) > T  <=>  n mod l notin F_l (l>y),
    exact F_l; compare exact product with direct Monte Carlo
10. plain (no splitting) Monte Carlo of delta*(T) at T = 127, 511 vs the split estimates
"""
import sys
import math
import random
from math import gcd, log, prod

import numpy as np
from sympy import factorint, isprime, primerange, jacobi_symbol, nextprime, divisors
from sympy.ntheory.modular import crt


def Rset(M):
    A = (M + 1) // 4
    return {(-4 * D) % M for D in divisors(A * A)}


ROWS = {}


def W(n, T):
    """W(n) via (58.3), capped: returns T+1 if > T."""
    for M in range(3, T + 1, 4):
        if M not in ROWS:
            ROWS[M] = Rset(M)
        if n % M in ROWS[M]:
            return M
    return T + 1


def Lstar(T):
    L = 24
    for M in range(3, T + 1, 4):
        L = L * M // gcd(L, M)
    return L


def rat_set(x, q):
    out = set()
    ps = list(factorint(x).items())
    divs = divisors(x)
    for u in divs:
        for v in divs:
            if gcd(u, v) == 1 and x % (u * v) == 0 and gcd(v, q) == 1:
                out.add(u * pow(v, -1, q) % q)
    return out


def main():
    ok = True
    # 1
    bad = [M for M in range(3, 20001, 4) if 1 in Rset(M)]
    print('1. M<=20000 with 1 in R(M):', bad[:5], 'count', len(bad))
    ok &= not bad
    # 2
    for T in (100, 1000, 10000, 100000):
        print(f'2. T={T}: log L*(T)/T = {log(Lstar(T)) / T:.4f}')
    # 3
    mordell = {1, 121, 169, 289, 361, 529}
    for T in (15, 23, 31, 39, 47):
        L = Lstar(T)
        p = L + 1
        while not isprime(p):
            p += L
        w = W(p, 4 * T + 200)
        print(f'3. T={T}: p={p}, W(p)={w}, W>T: {w > T}, Mordell-hard: {p % 840 in mordell}, '
              f'T/log p={T / log(p):.3f}')
        ok &= w > T and p % 840 in mordell
    # 4, 5
    v4 = v5 = n4 = n5 = 0
    for p in primerange(17, 6000):
        if p % 8 != 1:
            continue
        for q in range(3, min(3 * p, 400), 4):
            x = (p + q) // 4
            fx = factorint(x)
            for r in fx:
                n4 += 1
                if jacobi_symbol(r, q) != jacobi_symbol(r, p):
                    v4 += 1
            if isprime(q):
                n5 += 1
                # subgroup generated by prime factors of x in (Z/q)^*
                H = {1}
                frontier = [1]
                gens = [r % q for r in fx]
                while frontier:
                    h = frontier.pop()
                    for g in gens:
                        k = h * g % q
                        if k not in H:
                            H.add(k)
                            frontier.append(k)
                has_qnr = any(jacobi_symbol(r, p) == -1 for r in fx)
                if ((q - 1) in H) != has_qnr:
                    v5 += 1
    print(f'4. Lemma 8.2: {n4} (p,q,r) checks, violations {v4}')
    print(f'5. Cor 8.3(b): {n5} prime windows, violations {v5}')
    ok &= v4 == 0 and v5 == 0
    # 6
    v6 = n6 = n6_2 = 0
    for p in primerange(5, 20000):
        if p % 4 != 1:
            continue
        n = next(l for l in primerange(2, p) if jacobi_symbol(l, p) == -1)
        q0 = (-p) % (4 * n)
        for j in range(6):
            q = q0 + 4 * n * j
            if q <= 0:
                continue
            n6 += 1
            n6_2 += n == 2
            x, rem = divmod(p + q, 4)
            if not (q % 4 == 3 and rem == 0 and x % n == 0 and jacobi_symbol(n, q) == -1):
                v6 += 1
    print(f'6. Lemma 9.1: {n6} seeded windows ({n6_2} with n_p=2), violations {v6}')
    ok &= v6 == 0
    # 7
    v7 = 0
    rng = random.Random(1)
    for _ in range(40):
        q = rng.choice([3, 7, 11, 15, 19, 23, 27, 35, 39])
        Q = rng.choice([5, 7, 8, 9, 12, 35, 840])
        c = rng.choice([u for u in range(1, Q) if gcd(u, Q) == 1 and u % gcd(Q, 4) == 1 % gcd(Q, 4)])
        r = nextprime(q)
        while r % q != q - 1 or (2 * q * Q) % r == 0:
            r = nextprime(r)
        mods, res = [Q, 4, r], [c, 1, (-q) % r]
        if Q % 4 == 0:
            mods, res = [Q, r], [c, (-q) % r]
        a, mod = crt(mods, res)
        a, mod = int(a), int(mod)
        found = 0
        p = a
        while found < 3:
            p += mod
            if isprime(p) and p > 3 * q:
                found += 1
                x = (p + q) // 4
                if (q - 1) % q not in rat_set(x, q):
                    v7 += 1
    print(f'7. Lemma 11.3: 120 constructed primes, windows without -1 in Rat_q: {v7}')
    ok &= v7 == 0
    # 8
    v8 = n8 = 0
    for T in (60, 90, 150):
        for l in primerange(5, T // 3 + 1):
            if l % 4 != 1:
                continue
            A = (3 * l + 1) // 4
            rs = [r for r in factorint(A) if r % 3 == 2]
            if not rs:
                continue
            r = rs[0]
            M = 3 * l
            cls = (-4 * r) % M
            assert cls % 3 == 1 and cls in Rset(M)
            # combined with c = 1 mod 24*... (any certificate class avoiding l): take c=1 mod 24
            a, mod = crt([24, l], [1, cls % l])
            a, mod = int(a), int(mod)
            p = a
            while not isprime(p):
                p += mod
            n8 += 1
            if not (p % M == cls and W(p, M) <= M):
                v8 += 1
    print(f"8. Prop 11.2'' step 3: {n8} explicit atoms, failures {v8}")
    ok &= v8 == 0
    # 9
    T, y = 4095, 101
    Qy = 24
    for l in primerange(3, y + 1):
        e = 1
        while l ** (e + 1) <= T:
            e += 1
        Qy = Qy * l ** e // gcd(Qy, l ** e)
    F = {}
    for l in primerange(y + 1, T + 1):
        Fl = set()
        for m in range(1, T // l + 1):
            M = m * l
            if M % 4 != 3:
                continue
            A = (M + 1) // 4
            for D in divisors(A * A):
                if (-4 * D - 1) % m == 0:
                    Fl.add((-4 * D) % l)
        F[l] = Fl
    exact = prod(1 - len(F[l]) / (l - 1) for l in F)
    rng2 = np.random.default_rng(3)
    nsamp, surv, mism = 20000, 0, 0
    big = prod(F) # noqa (not used)
    for _ in range(nsamp):
        # n = 1 mod Qy, uniform unit residues mod each prime l in (y, T]
        resl = {l: int(rng2.integers(1, l)) for l in F}
        a, mod = crt([Qy] + list(resl), [1] + list(resl.values()))
        n = int(a)
        direct = W(n, T) > T
        local = all(resl[l] not in F[l] for l in F)
        mism += direct != local
        surv += local
    print(f'9. Lemma 11.7 reduction at T={T}, y={y}: max |F_l|/l = '
          f'{max(len(F[l]) / l for l in F):.3f}; exact conditional density {exact:.4f}, '
          f'MC {surv / nsamp:.4f}; direct-vs-local mismatches {mism}/{nsamp}')
    ok &= mism == 0
    # 9b: the important direction on local SURVIVORS (n mod l outside F_l for every l > y)
    mism2 = 0
    for _ in range(2000):
        resl = {}
        for l in F:
            while True:
                r0 = int(rng2.integers(1, l))
                if r0 not in F[l]:
                    break
            resl[l] = r0
        a, mod = crt([Qy] + list(resl), [1] + list(resl.values()))
        mism2 += not (W(int(a), T) > T)
    print(f'9b. local survivors with W(n) <= T (should be 0): {mism2}/2000')
    ok &= mism2 == 0
    # 10
    for T, nsamp in ((127, 400000), (511, 3000000)):
        Ms = list(range(3, T + 1, 4))
        tabs = []
        for M in Ms:
            t = np.zeros(M, dtype=bool)
            for c in Rset(M):
                t[c] = True
            tabs.append(t)
        ps = list(primerange(3, T + 1))
        kmax = {l: int(math.floor(math.log(T) / math.log(l))) for l in ps}
        alive = 0
        rng3 = np.random.default_rng(10 + T)
        chunk = 200000
        done = 0
        while done < nsamp:
            k = min(chunk, nsamp - done)
            res = {}
            for l in ps:
                mod = l ** kmax[l]
                if l == 3:
                    res[l] = 1 + 3 * rng3.integers(0, mod // 3, size=k)
                else:
                    x = rng3.integers(0, mod // l, size=k) * l + rng3.integers(1, l, size=k)
                    res[l] = x
            keep = np.ones(k, dtype=bool)
            for M, t in zip(Ms, tabs):
                r = np.zeros(k, dtype=np.int64)
                for l, e in factorint(M).items():
                    le = l ** e
                    c = (M // le) * pow(M // le, -1, le)
                    r = (r + (res[l] % le) * c) % M
                keep &= ~t[r]
            alive += int(keep.sum())
            done += k
        d = alive / nsamp
        print(f'10. plain MC delta*({T}) = {d:.3e} +- {math.sqrt(alive) / nsamp:.1e} (n={nsamp})')
    print('OK' if ok else 'FAILED')


if __name__ == '__main__':
    main()
